esphome:
  name: desktop-power

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CXTmUTSWQdlZDg0wQV4+lm0HnpjF4+vxzAaaYaEYy94="

ota:
  password: "b251edff263f61a2647e7873a460a94f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Desktop-Power Fallback Hotspot"
    password: !secret hotspot_wifi_password

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password

switch:
  - platform: gpio
    pin: D5
    name: "Desktop Power Button"
    id: powerbutton_relay
    on_turn_on:
      - delay: 250ms
      - switch.turn_off: powerbutton_relay

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s